name: Keep App Awake via Commit

on:
  schedule:
    # Runs every 4 hours, same as before
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  dummy_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This allows the workflow to push a commit back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Dummy File to Force Commit
        run: |
          # Create or update a tiny file with the current timestamp
          echo "$(date)" > .streamlit-wake-up.txt
          
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .streamlit-wake-up.txt
          # Only proceed if there are changes to commit
          if git diff --cached --exit-code; then
            echo "No changes to commit. App should be awake from last run."
          else
            git commit -m "🤖 [Automated] Keep app awake via commit"
            git push
            echo "Successfully pushed dummy commit."
          fi
