name: Wake Streamlit App

on:
  schedule:
    # Runs every 4 hours (e.g., 04:00, 08:00, 12:00, etc., UTC).
    # This keeps the app awake by resetting the 12-hour sleep timer.
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping to the Streamlit app
        run: |
          # *** REPLACE THIS URL with your app's actual URL ***
          APP_URL="https://disseration.streamlit.app/"

          echo "Pinging ${APP_URL}..."

          # Use curl to make a simple request
          curl -sS -L "${APP_URL}" > /dev/null

          echo "Ping complete. Timer should be reset."
