name: Wake Streamlit App

on:
  schedule:
    # Runs every 4 hours (e.g., 04:00, 08:00, 12:00, etc., UTC).
    # This keeps the app awake by resetting the 12-hour sleep timer.
    - cron: '0 */4 * * *'
  # Allows for manual testing via the GitHub Actions UI
  workflow_dispatch:

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping to the Streamlit app
        run: |
          # Pinging the healthcheck.txt file bypasses the redirect loop from the login page.
                    # *** TARGET THE STATIC FOLDER PATH ***
          APP_URL="https://disseration.streamlit.app/app/static/healthcheck.txt"

          
          echo "Attempting to wake up the app at ${APP_URL}..."
          
          # Use curl with increased timeout (30s) and follow redirects (-L)
          # --max-time 30: Gives the Streamlit app 30 seconds to wake up and respond.
          curl -sS -L --max-time 30 "${APP_URL}" > /dev/null
          
          echo "Ping command finished successfully."
